version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ticket_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ticketpass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticket_management"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    ports:
      - "5050:5050"
    environment:
      PORT: 5050
      DATABASE_URL: postgresql://postgres:ticketpass123@postgres:5432/ticket_management
      NODE_ENV: production
      SESSION_SECRET: LnaywtczXVRNdKoW4BA9RgMhGSwU2EgtxLJQtb5o2OFxAXyV/hIrpBhfAigw7pM7uzHLSxIypM4yP3ewNBRjPg==

      REPLIT_DOMAINS: localhost:5050,your-domain.com
      REPL_ID: d2b0a110-7413-403c-ac19-f2acdef4136c
      ISSUER_URL: https://replit.com/oidc
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: